import {Platform, StyleSheet, Text, View} from 'react-native';
import Theme from '../../../theme/Theme';
import {RH, RW} from '../../../components/store/ExternalLibrary';
const styles = StyleSheet.create({
  basic_info_container: {
    backgroundColor: Theme.COLORS.LIGHT_BLUE,
    borderRadius: RH(1),
    borderWidth: RH(0.2),
    borderColor: Theme.COLORS.BLUE,
    padding: RH(2),
  },
  software_container: {
    borderWidth: RH(0.2),
    borderColor: Theme.COLORS.BLUE,
    borderRadius: RH(1),
    paddingVertical: RH(1),
  },
  dropdown_img: {
    aspectRatio: 1,
    resizeMode: 'contain',
    width: RH(1.8),
    alignSelf: 'flex-end',
  },
  dropdown_img_180: {
    aspectRatio: 1,
    resizeMode: 'contain',
    width: RH(1.8),
    alignSelf: 'flex-end',
    transform: [{rotate: '180deg'}],
  },
  gradient_con_hours: {
    borderRadius: RH(1),
    width: '45%',
    // flex: 1,
    margin: RH(1),
    minWidth: RH(13),
  },

  dropdown_container: {
    backgroundColor: Theme.COLORS.WHITE,
    borderRadius: RH(1),
    borderColor: Theme.COLORS.BLUE,
    paddingHorizontal: RH(2),
    borderWidth: RH(0.2),
    paddingVertical: RH(2),
  },
  gradient_con: {
    borderRadius: RH(1),
    // flex: 1,
    margin: RH(1),
    minWidth: RH(13),
  },
  input_style: {
    borderColor: Theme.COLORS.BLUE,
    borderWidth: RH(0.2),
    // padding: RH(2),
    paddingHorizontal: RH(2),
    height: RH(6.8),
    width: '100%',
    color: Theme.COLORS.BLACK,
    fontFamily: Theme.FONT_FAMILY.BOLD,
    fontSize: RH(1.8),
    borderRadius: RH(1.2),
    backgroundColor: Theme.COLORS.WHITE,
  },
  btn_container: {
    padding: RH(1.6),
  },
  non_gradient: {
    borderColor: Theme.COLORS.BLUE,
    // borderWidth: RH(0.2),
    borderRadius: RH(30),
    backgroundColor: Theme.COLORS.WHITE,
  },
  gradient: {
    borderRadius: RH(30),
    // borderWidth: RH(0.2),
    borderColor: 'transparent',
  },
  add_btn: {
    position: 'absolute',
    right: RH(1),
    // top: Platform.OS === 'ios' ? RH(3.8) : RH(4.5),
    backgroundColor: Theme.COLORS.DARK_BLUE,
    paddingHorizontal: RH(3),
    // paddingVertical: RH(1.9),
    borderRadius: RH(1),
    height: '100%',
    justifyContent: 'center',
  },
  benefit_text_width: {
    width: '77%',
  },
  checked_img: {
    aspectRatio: 1,
    resizeMode: 'contain',
    width: RH(2.7),
  },
  small_close: {
    aspectRatio: 1,
    resizeMode: 'contain',
    height: RH(4),
    // backgroundColor: 'red',
  },
  gap: {
    marginRight: RH(1.6),
  },
  arrow_right: {
    aspectRatio: 1,
    resizeMode: 'contain',
    width: RH(2),
  },
  input_area: {
    height: RH(25),
    backgroundColor: Theme.COLORS.WHITE,
    borderRadius: RH(1),
    borderColor: Theme.COLORS.BLUE,
    borderWidth: RH(0.2),
    padding: RH(2),
    fontFamily: Theme.FONT_FAMILY.BOLD,
    color: Theme.COLORS.BLACK,
    fontSize: RH(1.8),
    textAlignVertical: 'top',
  },
  box: {
    backgroundColor: Theme.COLORS.WHITE,
    paddingHorizontal: RH(2),
    paddingVertical: RH(0.5),
    margin: RH(1),
    alignItems: 'center',
    borderRadius: RH(10),
    minWidth: RH(8),
    borderColor: Theme.COLORS.BLUE,
    borderWidth: RH(0.2),
  },

  cancel_con: {
    backgroundColor: Theme.COLORS.RED,
    padding: RH(0.6),
    borderRadius: RH(0.4),
  },
  confirm_con: {
    backgroundColor: Theme.COLORS.DARK_GREEN,
    padding: RH(0.6),
    borderRadius: RH(0.4),
  },
  picker_text: {
    color: Theme.COLORS.WHITE,
    fontFamily: Theme.FONT_FAMILY.MEDIUM,
    fontSize: RH(1.7),
  },
  date_picker_box: {
    flexDirection: 'row',
    alignItems: 'center',
    position: 'absolute',
    gap: RH(2),
    right: RH(1),
    top: RH(1),
  },
  input_width: {
    // width: '78%',
  },
  date_picker_container: {
    backgroundColor: Theme.COLORS.BLUE,
    position: 'absolute',
    justifyContent: 'center',
    alignSelf: 'center',
    alignItems: 'center',
    bottom: 0,
    borderRadius: RH(1),
    width: '86%',
  },

  mg_bottom: {
    marginBottom: RH(5),
  },

  box_active: {
    backgroundColor: Theme.COLORS.DARK_BLUE,
    paddingHorizontal: RH(2),
    paddingVertical: RH(0.5),
    margin: RH(1),
    alignItems: 'center',
    borderRadius: RH(10),
    minWidth: RH(8),
    borderColor: Theme.COLORS.DARK_BLUE,
    borderWidth: RH(0.2),
  },
  flex_row: {flexWrap: 'wrap', flexDirection: 'row'},
  calendar_img: {
    aspectRatio: 1,
    resizeMode: 'contain',
    width: RH(2.6),
  },
  doc_icon: {
    aspectRatio: 1,
    resizeMode: 'contain',
    height: RH(2.5),
  },
  check_box_img: {
    aspectRatio: 1,
    resizeMode: 'contain',
    width: RH(3),
  },
  image_container: {
    backgroundColor: Theme.COLORS.WHITE,
    borderRadius: RH(10),
    padding: RH(1),
  },
  dropdown_box: {
    backgroundColor: Theme.COLORS.WHITE,
    padding: RH(1),
    borderRadius: RH(1),
    borderColor: Theme.COLORS.BLUE,
    borderWidth: RH(0.2),
    height: RH(20),
    overflow: 'scroll',
    marginTop: RH(0.2),
  },
  border_bottom: {
    borderBottomColor: Theme.COLORS.MEMIUM_GREY,
    borderBottomWidth: RH(0.1),
    marginVertical: RH(0.7),
  },
});
export default styles;
