export default {
  FONT_FAMILY: {
    BLACK: 'Mulish-Black',
    BOLD: 'Mulish-Bold',
    EXTRA_BOLD: 'Mulish-ExtraBold',
    EXTRA_LIGHT: 'Mulish-ExtraLight',
    LIGHT: 'Mulish-Light',
    MEDIUM: 'Mulish-Medium',
    REGULAR: 'Mulish-Regular',
    SEMI_BOLD: 'Mulish-SemiBold',
  },
  COLORS: {
    WHITE: '#fff',
    BLACK: '#353434',
    BLUE: '#83ABE7',
    LIGHT_BLUE: '#E1EDFF',
    DARK_BLUE: '#0165fc',
    GREY: 'grey',
    LIGHT_GREY: '#EAEAEA',
    MEMIUM_GREY: '#CCCCCC',
    RED: '#F46262',
    DARK_RED: '#F41515',
    LIGHT_RED: '#FFEBEB',
    LIGHT_GREEN: '#E8F9EF',
    DARK_GREEN: '#38C061',
    LIGHT_YELLOW: '#FEF5E6',
    DARK_YELLOW: '#F59E0B',
    EXTRA_LIGHT_BLUE: '#E6F0FF',
  },
  FONTSIZE: {},
};
